listen: ":8001"
# log_file: /var/log/download-proxy/download-proxy.log

secret: "change-this-secret"

max_expire_seconds: 3600

allowed_domains:
  - github.com
  - githubusercontent.com
  - githubassets.com
  - githubcopilot.com

